---

- name: install ansible dependencies
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
  - python-httplib2

- name: download
  get_url:
    url="http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb"
    dest=/home/{{ ansible_ssh_user }}/influxdb.deb

- name: update sources
  sudo: yes
  apt: update_cache=yes

- name: install
  sudo: yes
  apt: deb="/home/{{ ansible_ssh_user }}/influxdb.deb"

- name: config
  sudo: yes
  template:
    src=config.j2
    dest=/opt/influxdb/shared/config.toml
  notify: restart influxdb

- name: create metrics db
  uri:
    url="http://{{ private_ip }}:8086/db?u=root&p=root"
    method=POST
    body="{\"name\"{{':'}} \"metrics\"}"
    HEADER_Content-Type="application/json"
    status_code=201
    dest=/home/{{ ansible_ssh_user }}/.influxdbcreated
    creates=/home/{{ ansible_ssh_user }}/.influxdbcreated

- name: open firewall for private ip udp
  sudo: yes
  when: private_ip is defined
  ufw: rule=allow port=4444 proto=udp to_ip={{ private_ip }}
