---

- name: remove i386 arch
  sudo: yes
  command:
    dpkg --remove-architecture i386

- name: set repo key
  sudo: yes
  apt_key:
    url: 'https://repos.influxdata.com/influxdb.key'
    state: present

- name: add repo
  sudo: yes
  apt_repository:
    repo: 'deb https://repos.influxdata.com/ubuntu trusty stable'
    state: present

- name: update sources
  sudo: yes
  apt: update_cache=yes

- name: install package
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - influxdb
  notify: start influxdb

- name: config
  sudo: yes
  template:
    src=influxdb.j2
    dest=/etc/influxdb/influxdb.conf
  notify: restart influxdb

- name: create udp db
  ignore_errors: yes
  command:
    influx --host {{ private_ip }} -execute 'CREATE DATABASE udp'

- name: open firewall for private ip udp
  sudo: yes
  when: private_ip is defined
  ufw: rule=allow port=4444 proto=udp to_ip={{ private_ip }}
