---

- name: set repo key
  sudo: yes
  apt_key:
    url: 'https://packagecloud.io/gpg.key'
    state: present

- name: add repo
  sudo: yes
  apt_repository:
    repo: 'deb https://packagecloud.io/grafana/stable/debian/ wheezy main'
    state: present

- name: update sources
  sudo: yes
  apt: update_cache=yes

- name: install package
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - grafana
  notify: start grafana

- name: config
  sudo: yes
  template:
    src=grafana.j2
    dest=/etc/grafana/grafana.ini
  notify: restart grafana

- name: open firewall
  sudo: yes
  ufw: rule=allow port=3000 proto=tcp

- name: run grafana at boot
  sudo: yes
  command:
    update-rc.d grafana-server defaults 95 10
