---

- name: download
  get_url:
    url="https://grafanarel.s3.amazonaws.com/builds/grafana_2.0.0-beta1_amd64.deb"
    dest=/home/{{ ansible_ssh_user }}/grafana.deb

- name: update sources
  sudo: yes
  apt: update_cache=yes

- name: install
  sudo: yes
  apt: deb="/home/{{ ansible_ssh_user }}/grafana.deb"
  notify: restart

- name: config
  sudo: yes
  template:
    src=grafana.j2
    dest=/etc/grafana/grafana.ini
  notify: restart

- name: open firewall
  sudo: yes
  ufw: rule=allow port=3000 proto=tcp
