---

- name: install dependencies
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - gcc
    - make
    - libssl-dev
    - zlib1g-dev
    - e2fslibs-dev

- name: download
  get_url:
    url="https://www.tarsnap.com/download/tarsnap-autoconf-1.0.36.1.tgz"
    dest=/home/{{ ansible_ssh_user }}/tarsnap.tgz

- name: unpack
  unarchive:
    src=/home/{{ ansible_ssh_user }}/tarsnap.tgz
    dest=/home/{{ ansible_ssh_user }}/
    copy=no
    creates=/home/{{ ansible_ssh_user }}/tarsnap-autoconf-1.0.36.1/configure

- name: configure
  sudo: yes
  command:
    ./configure
    chdir=/home/{{ ansible_ssh_user }}/tarsnap-autoconf-1.0.36.1/
    creates=/home/{{ ansible_ssh_user }}/tarsnap-autoconf-1.0.36.1/config.h

- name: make
  sudo: yes
  command:
    make all install clean
    chdir=/home/{{ ansible_ssh_user }}/tarsnap-autoconf-1.0.36.1/
    creates=/usr/local/bin/tarsnap

- name: copy key
  sudo: yes
  copy:
    src=tarsnap_keys/{{ hostname }}.key
    dest=/root/.tarsnap.key
    mode=0600

- name: copy config file
  sudo: yes
  template:
    src=tarsnaprc.j2
    dest=/root/.tarsnaprc

- name: create bin folder
  sudo: yes
  file: path=/root/bin state=directory

- name: copy db dump script
  sudo: yes
  template:
    src=db_dump.j2
    dest=/root/bin/db_dump.sh
    mode=0700

- name: copy tarsnap hourly script
  sudo: yes
  template:
    src=hourly.j2
    dest=/root/bin/hourly.sh
    mode=0700

- name: copy tarsnap weekly script
  sudo: yes
  template:
    src=weekly.j2
    dest=/root/bin/weekly.sh
    mode=0700

- name: add hourly cron
  sudo: yes
  cron:
    name="tarsnap hourly backup"
    user="root"
    minute="1"
    job="/root/bin/hourly.sh >> /var/log/backup.log 2>&1"
    state=present

- name: add weekly cron
  sudo: yes
  cron:
    name="tarsnap weekly backup"
    user="root"
    weekday="1"
    job="/root/bin/weekly.sh >> /var/log/backup.log 2>&1"
    state=present
